Attribute VB_Name = "modMaps"

Public Sub Map_Intro()

  Map(0) = "------------------------------------------------"
  Map(1) = "------------------------------------------------"
  Map(2) = "------------------------------------------------"
  Map(3) = "------------------------------------------------"
  Map(4) = "------------------------------------------------"
  Map(5) = "------------------------------------------------"
  Map(6) = "------QDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDW------"
  Map(7) = "------EGBBBGGBBBGGGBBBGGGBBBGGGBBBGGGBBBGR------"
  Map(8) = "------EGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGR------"
  Map(9) = "------EGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGR------"
 Map(10) = "------EGBBBGGBBBGGGBBBGGGBBBGGGBBBGGGBBBGR------"
 Map(11) = "------EGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGR------"
 Map(12) = "------EGBBBGGBBBGGGBBBGGGBBBGGGBBBGGGBBBGR------"
 Map(13) = "------EGBBBGGBBBGGGBBBGGGBBBGGGBBBGGGBBBGR------"
 Map(14) = "------EGBBBGGBBBGGGBBBGGGBBBGGGBBBGGGBBBGR------"
  

End Sub

Public Sub Map_A1()
            
   Map(0) = "------------------------------------------------------------------------------------------------"
   Map(1) = "------------------------------------------------------------------------------------------------"
   Map(2) = "------------------------------------------------------------------------------------------------"
   Map(3) = "-----------------------------------------------------------------------------------------------------------"
   Map(4) = "-----------------------------------------------------------------------------------------------------------"
   Map(5) = "-----------------------------------------------------------------------------------------------------------"
   Map(6) = "-----------------------------------------------------------------------------------------------------------"
   Map(7) = "------GGGGGGGGGBGBGGBGGGGGBGBGGBBBGGBGGGBGGGGBGGGGBGGGGGBGGGGGBBGGGGGGGGGGGGBBGBGBGGGBGBGBGGGGBBGGGGGGG----"
   Map(8) = "------GGGGGGGGGGGGGGBGBGGGGGBGBBGGGBGGBGBBGGBGGGGBGGGGGBGGGGGBGGBGGGBGGGGGGGGBGGBBBGGGBGGGGGBBBGGGGBBGG----"
   Map(9) = "------GGGGGGGGGGBGGBGGGGGBGGGGGBGGGGBGGGBGGGGBGGGBGGGGGBBBGGBGGGGGGGGBBBGGGGGBGBBGGGBBBGBGBGBGGGGGGGBGG----"
  Map(10) = "------GBGBGGGGGGGGBGBGGGBGGGBGBGBGGGGGGGBGGBGGGGGBBGGGGBGGGGGBGGGBGGBGGBBGGBGGGGBBGBBBGGGBGGBGGGGGBGGGG----"
  Map(11) = "------GBGGGGGGGGGGGBGGGBGGGGGBGGBGGGGBGGGGBGGGGGGGBGGGGBGBGGGGGGGBGGGBGGBGGBGGGBGGGGGBGGGBGBGGGGBBGGGGB----"
  Map(12) = "------GGGGBGGBGBGBGGGGGGBGGGGBGGBGBBGBBGBGBGBGGBGBGGGGGGBGBGGGGGBGGGGBGGGBGBBBBGGBGGBBBGBBBBGGGGBGBGGGG----"
  Map(13) = "------GGBGGGGGGBBGGGGGBGGGGGGGGGGGBGGGGBGGGBGGGGBGGGGGGGGBGGGGGGGGGGBGBGGGGBBGGBGGGGBBGGGGBBGGGBGGGGBBG----"
  Map(14) = "------GGBGGGGBGGGGGGGGGGGGGBGGBGBGBGBGGGBGGGBGGGGGGGBGGGGGBBBBBBGGBBGGGGGGGGGGBBBGBBGGGGBBGBGBGGGGGBGGG----"
  Map(15) = "------GGGGGGBBGGGBGBBBGGGBGGGBGGGGBBGBBGBGGBGBGGBBBGBGGBGGGBGGGBGBBGBBGGGGGBBBBGBGGGGGGGGGGGGBGGGGGGBBB----"
  Map(16) = "------GGGGGGGBGBGBGBGGGGGGGGGBGGGGGBGGBGBGGGGGGGGGBGBGBGBGGBGGGGBBGBBBGGGGGGGBBBGGGGGBGBBBBGGGBBGGBBGGG----"
  Map(17) = "------GGBGBGGGGGGGGGGGGBBGGGBGGGGGBGGGBGGGGGGGGGGBGGGGBBBGBGBGGGGBGBGGGGGGGGGGBBBBBGBBBBGGGGBGGBGGGGGBB----"
  Map(18) = "------GGGBGBBGGGGGGGGBGGGBGGGGBGGGGGGGGGGGGGGGGGGBBGGGGBGGGGGGGGGGGGGGGGGGGBBGGGGBBGGGGGGBBGGGGGBGGGBBB----"
  Map(19) = "------GGGBGBGBGBGGGBGGBGBGGGBGBGGGBGGBBGBGBBBGGGBGBGGBGBBBGGGGBBGGBGBBBBBBBGGGGGGBBGGBBGGBGGGGGGBBGGGGG----"
  Map(20) = "------GGGGGBGBGGGBBBBGGBBGGGGBGBGGGGGBBGBBBBGGGGGBGBGGBBBGGGGGBBGBGBBBGGGGGBGGBBGGGBBBGGGBGBBGGGGBGGGGG----"
  Map(21) = "------GGGGGBBBBBGGGGGBGBBGBBBGBGBBBBGGGGGGGGGGGBBGGBGBGGGGBBBBGGBBBBBGGGGBGBGBBGBGBGGGGGGGGGGGGBGGGGGGB----"
  Map(22) = "------GGGBBGBGBBBGGGGGGGBBGGGBGBBBGGGBGBBBGGGGGBGBBBGGGBBGBGGBGBGBGGGBGGBGGBGGBBGGGGGBBBBBBBGGBGGGGGBBB----"
  Map(23) = "------GGGBGBGBBGGGBGGGBGGGGBBBGGBGGGGGBGGBGGGGGBGGGBGGGGGBGBGGGBBGGBBGGGGGGBBGGGGBBBGGGGBBBGGGBBGGGGBBG----"
  Map(24) = "------GGGGBBBGGBGGGGBBGGGBGBBGBBGGGGBGBBBBGGGGBBBGBBBBBGGGGBGGGBGBBGGGGGGGGGGGBBGGGBBGBBGBGBGGBBBGGGGGG----"
  Map(25) = "------GGGBBBGGGBGBGBBGGGGBBBGGBBGGGBBBGBBBBGGGGGGBBBGGBBGGGGGBBGBBBBGGGGGGBGGBGGGGGGBGBGGGGGGGGBGGGBBGG----"
  Map(26) = "------GGBBBGGBGBGBGGBGGBGGGBBBGGBBBGGGBGBGBGGBBBGGGBBGBGBGGGBGBGGGBGBGGBBBGGGGBGGBGBBBBGGGGBGGGGGGGBBBB----"
  Map(27) = "------GGGBBGGGBGGGBGGGGBGGGBBGGGGBGGGGGGBGGGBGBBBGGGGGGGBGGGBGGBGBGGGBGGGBBGGGGGGGGGGBGGGBGGGGGGGGGGBBG----"
  Map(28) = "-----------------------------------------------------------------------------------------------------------"
  Map(29) = "-----------------------------------------------------------------------------------------------------------"
  Map(30) = "-----------------------------------------------------------------------------------------------------------"
            
End Sub
